language: ruby

dist: trusty
sudo: required

rvm:
  - 2.5.1
  - 2.4.4
  - 2.3.7

gemfile:
  - gemfiles/activerecord_5.2.gemfile
  - gemfiles/activerecord_5.1.gemfile
  - gemfiles/activerecord_5.0.gemfile
  - gemfiles/activerecord_4.2.gemfile

env:
  - DB=postgresql
  - DB=mysql
  - DB=mysql MYSQL_VERSION=5.7
  - DB=sqlite

before_install:
  - gem install bundler

script: WITH_ADVISORY_LOCK_PREFIX=$TRAVIS_JOB_ID bundle exec rake --trace

before_script:
  - bash .travis.install-mysql-5.7.sh
  - mysql -e 'create database with_advisory_lock_test'
  - psql -c 'create database with_advisory_lock_test' -U postgres